/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalysisRecord {
  'id' : bigint,
  'marketData' : MarketData,
  'timestamp' : bigint,
  'analysis' : TechnicalAnalysisResult,
}
export interface MarketData {
  'low' : number,
  'timeframe' : string,
  'high' : number,
  'close' : number,
  'open' : number,
  'volume' : number,
  'notes' : [] | [string],
  'symbol' : string,
}
export interface TechnicalAnalysisResult {
  'macdSignal' : string,
  'trend' : string,
  'movingAverageSignal' : string,
  'candlestickPattern' : string,
  'liquidityZone' : number,
  'momentum' : string,
  'reasoning' : string,
  'confidenceLevel' : string,
  'resistanceLevel' : number,
  'supportLevel' : number,
  'rsiSignal' : string,
  'stopLoss' : number,
  'tradeSignal' : string,
  'entryPrice' : number,
  'takeProfit1' : number,
  'takeProfit2' : number,
  'takeProfit3' : number,
  'riskRewardRatio' : number,
}
export interface _SERVICE {
  'analyzeMarketData' : ActorMethod<[MarketData], bigint>,
  'getAllAnalyses' : ActorMethod<[], Array<AnalysisRecord>>,
  'getAnalysesBySymbol' : ActorMethod<[string], Array<AnalysisRecord>>,
  'getAnalysesCount' : ActorMethod<[], bigint>,
  'getAnalysesInRange' : ActorMethod<[bigint, bigint], Array<AnalysisRecord>>,
  'getAnalysisById' : ActorMethod<[bigint], AnalysisRecord>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];