/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MarketData = IDL.Record({
  'low' : IDL.Float64,
  'timeframe' : IDL.Text,
  'high' : IDL.Float64,
  'close' : IDL.Float64,
  'open' : IDL.Float64,
  'volume' : IDL.Float64,
  'notes' : IDL.Opt(IDL.Text),
  'symbol' : IDL.Text,
});
export const TechnicalAnalysisResult = IDL.Record({
  'macdSignal' : IDL.Text,
  'trend' : IDL.Text,
  'movingAverageSignal' : IDL.Text,
  'candlestickPattern' : IDL.Text,
  'liquidityZone' : IDL.Float64,
  'momentum' : IDL.Text,
  'reasoning' : IDL.Text,
  'confidenceLevel' : IDL.Text,
  'resistanceLevel' : IDL.Float64,
  'supportLevel' : IDL.Float64,
  'rsiSignal' : IDL.Text,
  'stopLoss' : IDL.Float64,
  'tradeSignal' : IDL.Text,
  'entryPrice' : IDL.Float64,
  'takeProfit1' : IDL.Float64,
  'takeProfit2' : IDL.Float64,
  'takeProfit3' : IDL.Float64,
  'riskRewardRatio' : IDL.Float64,
});
export const AnalysisRecord = IDL.Record({
  'id' : IDL.Nat,
  'marketData' : MarketData,
  'timestamp' : IDL.Int,
  'analysis' : TechnicalAnalysisResult,
});

export const idlService = IDL.Service({
  'analyzeMarketData' : IDL.Func([MarketData], [IDL.Nat], []),
  'getAllAnalyses' : IDL.Func([], [IDL.Vec(AnalysisRecord)], ['query']),
  'getAnalysesBySymbol' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AnalysisRecord)],
      ['query'],
    ),
  'getAnalysesCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getAnalysesInRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(AnalysisRecord)],
      ['query'],
    ),
  'getAnalysisById' : IDL.Func([IDL.Nat], [AnalysisRecord], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MarketData = IDL.Record({
    'low' : IDL.Float64,
    'timeframe' : IDL.Text,
    'high' : IDL.Float64,
    'close' : IDL.Float64,
    'open' : IDL.Float64,
    'volume' : IDL.Float64,
    'notes' : IDL.Opt(IDL.Text),
    'symbol' : IDL.Text,
  });
  const TechnicalAnalysisResult = IDL.Record({
    'macdSignal' : IDL.Text,
    'trend' : IDL.Text,
    'movingAverageSignal' : IDL.Text,
    'candlestickPattern' : IDL.Text,
    'liquidityZone' : IDL.Float64,
    'momentum' : IDL.Text,
    'reasoning' : IDL.Text,
    'confidenceLevel' : IDL.Text,
    'resistanceLevel' : IDL.Float64,
    'supportLevel' : IDL.Float64,
    'rsiSignal' : IDL.Text,
    'stopLoss' : IDL.Float64,
    'tradeSignal' : IDL.Text,
    'entryPrice' : IDL.Float64,
    'takeProfit1' : IDL.Float64,
    'takeProfit2' : IDL.Float64,
    'takeProfit3' : IDL.Float64,
    'riskRewardRatio' : IDL.Float64,
  });
  const AnalysisRecord = IDL.Record({
    'id' : IDL.Nat,
    'marketData' : MarketData,
    'timestamp' : IDL.Int,
    'analysis' : TechnicalAnalysisResult,
  });
  
  return IDL.Service({
    'analyzeMarketData' : IDL.Func([MarketData], [IDL.Nat], []),
    'getAllAnalyses' : IDL.Func([], [IDL.Vec(AnalysisRecord)], ['query']),
    'getAnalysesBySymbol' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AnalysisRecord)],
        ['query'],
      ),
    'getAnalysesCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getAnalysesInRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(AnalysisRecord)],
        ['query'],
      ),
    'getAnalysisById' : IDL.Func([IDL.Nat], [AnalysisRecord], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };