/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MarketData {
    low: number;
    timeframe: string;
    high: number;
    close: number;
    open: number;
    volume: number;
    notes?: string;
    symbol: string;
}
export interface TechnicalAnalysisResult {
    macdSignal: string;
    trend: string;
    movingAverageSignal: string;
    candlestickPattern: string;
    liquidityZone: number;
    momentum: string;
    reasoning: string;
    confidenceLevel: string;
    resistanceLevel: number;
    supportLevel: number;
    rsiSignal: string;
    stopLoss: number;
    tradeSignal: string;
    entryPrice: number;
    takeProfit1: number;
    takeProfit2: number;
    takeProfit3: number;
    riskRewardRatio: number;
}
export interface AnalysisRecord {
    id: bigint;
    marketData: MarketData;
    timestamp: bigint;
    analysis: TechnicalAnalysisResult;
}
export interface backendInterface {
    analyzeMarketData(marketData: MarketData): Promise<bigint>;
    getAllAnalyses(): Promise<Array<AnalysisRecord>>;
    getAnalysesBySymbol(symbol: string): Promise<Array<AnalysisRecord>>;
    getAnalysesCount(): Promise<bigint>;
    getAnalysesInRange(startTime: bigint, endTime: bigint): Promise<Array<AnalysisRecord>>;
    getAnalysisById(id: bigint): Promise<AnalysisRecord>;
}
import type { AnalysisRecord as _AnalysisRecord, MarketData as _MarketData, TechnicalAnalysisResult as _TechnicalAnalysisResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async analyzeMarketData(arg0: MarketData): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeMarketData(to_candid_MarketData_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeMarketData(to_candid_MarketData_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllAnalyses(): Promise<Array<AnalysisRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnalyses();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnalyses();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalysesBySymbol(arg0: string): Promise<Array<AnalysisRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalysesBySymbol(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalysesBySymbol(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalysesCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalysesCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalysesCount();
            return result;
        }
    }
    async getAnalysesInRange(arg0: bigint, arg1: bigint): Promise<Array<AnalysisRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalysesInRange(arg0, arg1);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalysesInRange(arg0, arg1);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalysisById(arg0: bigint): Promise<AnalysisRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalysisById(arg0);
                return from_candid_AnalysisRecord_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalysisById(arg0);
            return from_candid_AnalysisRecord_n4(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AnalysisRecord_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalysisRecord): AnalysisRecord {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_MarketData_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketData): MarketData {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    marketData: _MarketData;
    timestamp: bigint;
    analysis: _TechnicalAnalysisResult;
}): {
    id: bigint;
    marketData: MarketData;
    timestamp: bigint;
    analysis: TechnicalAnalysisResult;
} {
    return {
        id: value.id,
        marketData: from_candid_MarketData_n6(_uploadFile, _downloadFile, value.marketData),
        timestamp: value.timestamp,
        analysis: value.analysis
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: number;
    timeframe: string;
    high: number;
    close: number;
    open: number;
    volume: number;
    notes: [] | [string];
    symbol: string;
}): {
    low: number;
    timeframe: string;
    high: number;
    close: number;
    open: number;
    volume: number;
    notes?: string;
    symbol: string;
} {
    return {
        low: value.low,
        timeframe: value.timeframe,
        high: value.high,
        close: value.close,
        open: value.open,
        volume: value.volume,
        notes: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.notes)),
        symbol: value.symbol
    };
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnalysisRecord>): Array<AnalysisRecord> {
    return value.map((x)=>from_candid_AnalysisRecord_n4(_uploadFile, _downloadFile, x));
}
function to_candid_MarketData_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MarketData): _MarketData {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: number;
    timeframe: string;
    high: number;
    close: number;
    open: number;
    volume: number;
    notes?: string;
    symbol: string;
}): {
    low: number;
    timeframe: string;
    high: number;
    close: number;
    open: number;
    volume: number;
    notes: [] | [string];
    symbol: string;
} {
    return {
        low: value.low,
        timeframe: value.timeframe,
        high: value.high,
        close: value.close,
        open: value.open,
        volume: value.volume,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        symbol: value.symbol
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
